### PR TITLE
Support puma 6

### PR DESCRIPTION
**Pull request by tricknotes**
This PR supports Puma 5 and 6.

Close https://github.com/yob/puma-plugin-statsd/issues/43

### CODE REVIEW

**Comment by tricknotes** [comment]
My application works fine on Puma 5 and 6 with this change.

**Review by yob — APPROVED** [review]
Thanks!

I've tested this on puma 5 and 6, and it all works as expected ✨

I'd like to release this as 2.4.0 in a week or two - is anyone keen to load `main` via git and dogfood the pre-released version on prod for me?

**Comment by epintos** [comment]
@yob @tricknotes  thanks for this! When are you planning to release 2.4.0?

**Comment by yob** [comment]
I've just released 2.4.0 with this PR - please let me know how it goes with both puma 5 and 6 ❤️

**Pull request merged**
