### PR TITLE
Submit `requests_count` as count rather than gauge

### PR DESCRIPTION
**Pull request by kimvsparrow**
A metric for Requests makes a lot more sense in Datadog (presumably other Statsd consumers as well) when typed as a Count type instead of a Gauge.  Datadog doesn't do a great job of transforming gauges into a rate.

Puma tallies the total number of requests it has handled since start.  This change tracks the previously reported total, and subtracts that from the current total, for a count of requests since the previous report.  Then we can change the type of the metric.

While this change makes sense to me, I'd consider it a breaking change.  It will require changes in monitoring from other users who already depend on the Gauge type.  So it's understandable if this doesn't fit in with your plans.

P.S.  I dig the recent Unix domain socket change.  I had to jump through some hoops to get around this same issue in our own infrastructure!

### CODE REVIEW

**Comment by yob** [comment]
Thanks for the great description, your reasoning is sound to me.

I'm not keen on a breaking change though - could we report this as a new metric with a different name?

**Comment by kimvsparrow** [comment]
Good idea!  Here are some potential names.  I don't have a strong opinion about it -- though I do prefer the ones that at least start with `requests` so it gets grouped with the existing `requests_count` metric.

* requests_count_per_interval
* requests_count_interval
* interval_requests_count
* requests_per_interval
* requests_count_increment
* incremental_requests_count

(What's that they say about the two hard things in programming?)

**Comment by yob** [comment]
None are as good as `requests_count`, but I guess that's the price we pay for backward compat.

What about just `requests`? If not, `requests_count_per_interval` is ok :+1:

**Comment by yob** [comment]
merged in #55

**Pull request closed without merging**
