### PR TITLE
Add unix socket connection support

### PR DESCRIPTION
**Pull request by rodzyn**
As written in the PR title

### CODE REVIEW

**Review by yob — COMMENTED** [review]
Interesting!

Purely out of curiosity, what's driving the need for this change? Is it just about preferring local unix sockets where possible?

**Comment by rodzyn** [comment]
> Interesting!
> 
> Purely out of curiosity, what's driving the need for this change? Is it just about preferring local unix sockets where possible?

I just wanted to add an option to connect via UNIX socket. In my case, we are using containers where their networking is isolated from the rest of the system, so the only way for them to talk to stated is for UNIX socket

**Comment by cwoodcox** [comment]
This is also useful with Datadog as it supports origin discovery so Datadog can better auto discover tags that it should apply when it ships data

**Comment by yob** [comment]
Thanks!

**Pull request merged**
